param([string]$ConfigPath)
Import-Module ../Modules/ADSync-Functions.psm1
Start-Transcript -Path ../Logs/StarterStaffLog.txt -Append
[xml]$Config=Get-Content $ConfigPath
$School=$Config.SchoolConfig.School
$CsvPath='../Logs/StarterStaff.csv'
$AccessToken=Invoke-RestMethod -Uri "$($School.BromcomAPI.BaseURL)/token" -Method Post -Body @{client_id=$School.BromcomAPI.ClientID;client_secret=$School.BromcomAPI.ClientSecret;grant_type='client_credentials'}
$Token=$AccessToken.access_token
$Headers=@{Authorization="Bearer $Token"}
$StaffData=Invoke-RestMethod -Uri "$($School.BromcomAPI.BaseURL)/$($School.BromcomAPI.InstanceID)/staff" -Headers $Headers
foreach($Staff in $StaffData){$Username=($Staff.LastName+$Staff.FirstName.Substring(0,1)).ToLower();$Password=Generate-PasswordFromDOB -DOB $Staff.DateOfBirth;try{$ExistingUser=Get-ADUser -Filter {Name -eq "$($Staff.FirstName) $($Staff.LastName)"};if(-not $ExistingUser){New-ADUser -Name "$($Staff.FirstName) $($Staff.LastName)" -SamAccountName $Username -UserPrincipalName "$Username@$($School.Domain)" -GivenName $Staff.FirstName -Surname $Staff.LastName -EmployeeID $Staff.EmployeeID -Title $Staff.JobTitle -Department $School.Department -Company $School.Company -Manager $Staff.LineManager -EmailAddress $Staff.Email -Path $School.OUPaths.StaffTeaching -Enabled $true -AccountPassword (ConvertTo-SecureString $Password -AsPlainText -Force);Set-ADUser -Identity $Username -Add @{proxyAddresses="SMTP:$($Staff.Email)"}}else{Set-ADUser -Identity $ExistingUser.DistinguishedName -EmployeeID $Staff.EmployeeID -EmailAddress $Staff.Email -Title $Staff.JobTitle -Department $School.Department -Company $School.Company -Manager $Staff.LineManager;Set-ADUser -Identity $ExistingUser.DistinguishedName -Add @{proxyAddresses="SMTP:$($Staff.Email)"}};$row=[PSCustomObject]@{Name="$($Staff.FirstName) $($Staff.LastName)";EmployeeID=$Staff.EmployeeID;Username=$Username;Email=$Staff.Email;Password=$Password};$row|Export-Csv -Path $CsvPath -Append -NoTypeInformation}catch{Write-Error "Error processing staff: $_"}}Send-GraphEmail -TenantID $School.GraphAPI.TenantID -ClientID $School.GraphAPI.ClientID -ClientSecret $School.GraphAPI.ClientSecret -To 'farnworthz@thequillcofetrust.org' -Subject "$($School.Name) - Staff Starters Processed" -Body 'Attached is the report of processed staff starters.' -Attachment $CsvPath;Stop-Transcript